import { ResumeData } from "./types";

export const resumeTemplates: Record<string, ResumeData> = {
  empty: {
    personalInfo: {
      name: "",
      email: "",
      phone: "",
      location: "",
      summary: "",
    },
    experience: [],
    education: [],
    skills: [],
  },
  modern: {
    personalInfo: {
      name: "Jordan Chen",
      email: "jordan.chen@email.com",
      phone: "+1 (555) 234-5678",
      location: "Seattle, WA",
      summary: "创新驱动的产品设计师，拥有5年用户体验设计经验。专注于创造直观、美观且功能强大的数字产品。擅长用户研究、原型设计和跨团队协作。",
    },
    experience: [
      {
        company: "TechFlow Design Studio",
        position: "高级产品设计师",
        startDate: "2022-03",
        endDate: "2024-01",
        description: "领导多个B2B产品的设计工作，用户满意度提升35%。建立设计系统，提高团队效率40%。指导初级设计师，推动设计文化建设。",
      },
      {
        company: "StartupXYZ",
        position: "UI/UX设计师",
        startDate: "2020-06",
        endDate: "2022-02",
        description: "从零开始设计移动应用，获得50万+下载量。进行用户研究和可用性测试，优化转化率25%。与开发团队紧密合作，确保设计实现质量。",
      },
    ],
    education: [
      {
        school: "华盛顿大学",
        degree: "设计学学士",
        field: "交互设计",
        graduationDate: "2020-06",
      },
    ],
    skills: [
      "Figma",
      "Sketch",
      "Adobe Creative Suite",
      "Prototyping",
      "User Research",
      "Design Systems",
      "HTML/CSS",
      "Agile/Scrum",
    ],
  },
  software: {
    personalInfo: {
      name: "Alex Johnson",
      email: "alex.johnson@email.com",
      phone: "(555) 123-4567",
      location: "San Francisco, CA",
      summary: "Senior Software Engineer with 5+ years of experience in full-stack development. Specialized in React, Node.js, and cloud technologies. Proven track record of delivering scalable solutions and leading development teams.",
    },
    experience: [
      {
        company: "Tech Solutions Inc.",
        position: "Senior Software Engineer",
        startDate: "2021-01",
        endDate: "2024-01",
        description: "Led development of microservices architecture, reducing deployment time by 40%. Mentored junior developers and implemented CI/CD pipelines.",
      },
      {
        company: "Digital Innovations",
        position: "Software Engineer",
        startDate: "2019-03",
        endDate: "2020-12",
        description: "Developed and maintained React applications serving 100K+ users. Implemented responsive designs and optimized performance.",
      },
    ],
    education: [
      {
        school: "University of California, Berkeley",
        degree: "Bachelor of Science",
        field: "Computer Science",
        graduationDate: "2019-05",
      },
    ],
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "AWS",
      "Docker",
      "GraphQL",
      "Git",
    ],
    style: [
      
    ]
  },
  marketing: {
    personalInfo: {
      name: "Sarah Miller",
      email: "sarah.miller@email.com",
      phone: "(555) 987-6543",
      location: "New York, NY",
      summary: "Creative Marketing Manager with 6+ years of experience in digital marketing and brand development. Proven success in developing and executing marketing strategies that drive engagement and ROI.",
    },
    experience: [
      {
        company: "Global Brands Co.",
        position: "Marketing Manager",
        startDate: "2020-06",
        endDate: "2024-01",
        description: "Led digital marketing campaigns resulting in 150% increase in online engagement. Managed a team of 5 marketing specialists and $1M annual budget.",
      },
      {
        company: "Creative Agency XYZ",
        position: "Digital Marketing Specialist",
        startDate: "2018-03",
        endDate: "2020-05",
        description: "Developed social media strategies for Fortune 500 clients. Increased client social media following by average of 200%.",
      },
    ],
    education: [
      {
        school: "New York University",
        degree: "Bachelor of Arts",
        field: "Marketing",
        graduationDate: "2018-05",
      },
    ],
    skills: [
      "Digital Marketing",
      "Social Media Management",
      "Content Strategy",
      "SEO/SEM",
      "Analytics",
      "Brand Development",
      "Project Management",
      "Adobe Creative Suite",
    ],
  },
  analyst: {
    personalInfo: {
      name: "Emily Wang",
      email: "emily.wang@email.com",
      phone: "+1 (555) 345-6789",
      location: "Boston, MA",
      summary: "资深数据分析师，具有4年商业智能和数据科学经验。擅长将复杂数据转化为可执行的商业洞察。精通统计分析、机器学习和数据可视化。",
    },
    experience: [
      {
        company: "DataInsights Corp",
        position: "高级数据分析师",
        startDate: "2021-08",
        endDate: "2024-01",
        description: "构建预测模型，提高销售预测准确率30%。开发自动化报告系统，节省团队80%的手工工作时间。与业务团队合作，识别关键增长机会。",
      },
      {
        company: "RetailTech Solutions",
        position: "数据分析师",
        startDate: "2020-01",
        endDate: "2021-07",
        description: "分析客户行为数据，优化营销策略，ROI提升45%。创建交互式仪表板，为管理层提供实时业务洞察。进行A/B测试，改进产品功能。",
      },
    ],
    education: [
      {
        school: "麻省理工学院",
        degree: "统计学硕士",
        field: "应用统计",
        graduationDate: "2019-12",
      },
    ],
    skills: [
      "Python",
      "R",
      "SQL",
      "Tableau",
      "Power BI",
      "Machine Learning",
      "Statistical Analysis",
      "Excel",
    ],
  },
  manager: {
    personalInfo: {
      name: "Michael Rodriguez",
      email: "michael.rodriguez@email.com",
      phone: "+1 (555) 456-7890",
      location: "Austin, TX",
      summary: "经验丰富的项目经理，拥有7年跨行业项目管理经验。专长于敏捷开发、团队领导和流程优化。成功交付价值超过500万美元的项目。",
    },
    experience: [
      {
        company: "Innovation Labs",
        position: "高级项目经理",
        startDate: "2020-09",
        endDate: "2024-01",
        description: "管理15人跨职能团队，按时按预算交付12个重大项目。实施敏捷方法论，项目交付效率提升50%。建立项目管理最佳实践，被公司采纳为标准流程。",
      },
      {
        company: "TechStart Inc",
        position: "项目经理",
        startDate: "2018-03",
        endDate: "2020-08",
        description: "协调产品开发生命周期，从概念到上市。管理利益相关者关系，确保项目目标一致。优化资源配置，降低项目成本20%。",
      },
    ],
    education: [
      {
        school: "德克萨斯大学奥斯汀分校",
        degree: "工商管理硕士",
        field: "项目管理",
        graduationDate: "2018-05",
      },
    ],
    skills: [
      "Project Management",
      "Agile/Scrum",
      "Team Leadership",
      "Risk Management",
      "Stakeholder Management",
      "Budget Planning",
      "JIRA",
      "Microsoft Project",
    ],
  },
  // 新增模板 - 初级前端开发工程师
  junior_frontend: {
    personalInfo: {
      name: "Jessica Liu",
      email: "jessica.liu@email.com",
      phone: "+1 (555) 234-5678",
      location: "Los Angeles, CA",
      summary: "Passionate Junior Frontend Developer with 1+ year of experience building responsive web applications. Strong foundation in HTML, CSS, JavaScript, and React. Eager to contribute to innovative projects and grow technical skills.",
    },
    experience: [
      {
        company: "WebDev Startup",
        position: "Junior Frontend Developer",
        startDate: "2023-06",
        endDate: "2024-01",
        description: "Developed responsive user interfaces using React and CSS. Collaborated with design team to implement pixel-perfect designs. Fixed bugs and improved website performance by 25%.",
      },
      {
        company: "FreelanceProjects",
        position: "Web Developer Intern",
        startDate: "2023-01",
        endDate: "2023-05",
        description: "Built landing pages for small businesses using HTML, CSS, and JavaScript. Learned version control with Git and collaborated on team projects.",
      },
    ],
    education: [
      {
        school: "UCLA Extension",
        degree: "Certificate",
        field: "Full Stack Web Development",
        graduationDate: "2023-01",
      },
      {
        school: "University of California, Los Angeles",
        degree: "Bachelor of Arts",
        field: "Psychology",
        graduationDate: "2022-06",
      },
    ],
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React",
      "Git",
      "Responsive Design",
      "Bootstrap",
      "Figma",
    ],
  },
  // 新增模板 - 高级产品经理
  senior_product: {
    personalInfo: {
      name: "David Kim",
      email: "david.kim@email.com",
      phone: "+1 (555) 345-6789",
      location: "Seattle, WA",
      summary: "Strategic Product Manager with 8+ years of experience driving product vision and execution at scale. Led cross-functional teams to deliver products used by millions of users. Expert in data-driven decision making and user-centric design.",
    },
    experience: [
      {
        company: "TechGiant Corp",
        position: "Senior Product Manager",
        startDate: "2020-03",
        endDate: "2024-01",
        description: "Led product strategy for flagship mobile app with 10M+ users. Increased user engagement by 40% through feature optimization. Managed roadmap and coordinated with engineering, design, and marketing teams.",
      },
      {
        company: "Growth Startup",
        position: "Product Manager",
        startDate: "2018-01",
        endDate: "2020-02",
        description: "Launched 3 major product features that drove 60% revenue growth. Conducted user research and A/B testing to validate product hypotheses. Built product requirements and worked closely with development team.",
      },
      {
        company: "Consulting Firm",
        position: "Business Analyst",
        startDate: "2016-06",
        endDate: "2017-12",
        description: "Analyzed market trends and competitive landscape for Fortune 500 clients. Created business cases and strategic recommendations that influenced product decisions.",
      },
    ],
    education: [
      {
        school: "Stanford University",
        degree: "Master of Business Administration",
        field: "Technology Management",
        graduationDate: "2016-06",
      },
      {
        school: "University of Washington",
        degree: "Bachelor of Science",
        field: "Computer Science",
        graduationDate: "2014-06",
      },
    ],
    skills: [
      "Product Strategy",
      "User Research",
      "Data Analysis",
      "A/B Testing",
      "Agile/Scrum",
      "SQL",
      "Figma",
      "JIRA",
      "Google Analytics",
      "Roadmap Planning",
    ],
  },
  // 新增模板 - 数据科学家
  data_scientist: {
    personalInfo: {
      name: "Dr. Maria Gonzalez",
      email: "maria.gonzalez@email.com",
      phone: "+1 (555) 456-7890",
      location: "San Francisco, CA",
      summary: "Experienced Data Scientist with PhD in Statistics and 6+ years applying machine learning to solve complex business problems. Specialized in predictive modeling, natural language processing, and deep learning. Published researcher with 15+ peer-reviewed papers.",
    },
    experience: [
      {
        company: "AI Research Lab",
        position: "Senior Data Scientist",
        startDate: "2021-01",
        endDate: "2024-01",
        description: "Developed machine learning models that improved recommendation accuracy by 35%. Led research initiatives in NLP and computer vision. Mentored junior data scientists and established ML best practices.",
      },
      {
        company: "FinTech Solutions",
        position: "Data Scientist",
        startDate: "2019-03",
        endDate: "2020-12",
        description: "Built fraud detection models reducing false positives by 50%. Implemented real-time scoring systems processing 1M+ transactions daily. Collaborated with engineering to deploy models in production.",
      },
      {
        company: "University Research Center",
        position: "Research Scientist",
        startDate: "2017-09",
        endDate: "2019-02",
        description: "Conducted statistical analysis for clinical trials. Published 8 research papers in top-tier journals. Developed novel algorithms for time series analysis.",
      },
    ],
    education: [
      {
        school: "Stanford University",
        degree: "Doctor of Philosophy",
        field: "Statistics",
        graduationDate: "2017-06",
      },
      {
        school: "UC Berkeley",
        degree: "Master of Science",
        field: "Applied Mathematics",
        graduationDate: "2013-05",
      },
    ],
    skills: [
      "Python",
      "R",
      "TensorFlow",
      "PyTorch",
      "SQL",
      "Spark",
      "AWS",
      "Docker",
      "Machine Learning",
      "Deep Learning",
      "NLP",
      "Statistics",
    ],
  },
  // 新增模板 - UI/UX设计师
  ux_designer: {
    personalInfo: {
      name: "Taylor Brown",
      email: "taylor.brown@email.com",
      phone: "+1 (555) 567-8901",
      location: "Portland, OR",
      summary: "Creative UI/UX Designer with 4+ years of experience crafting intuitive digital experiences. Passionate about user-centered design and accessibility. Proven track record of improving user satisfaction and conversion rates through thoughtful design solutions.",
    },
    experience: [
      {
        company: "Design Studio Pro",
        position: "UI/UX Designer",
        startDate: "2021-08",
        endDate: "2024-01",
        description: "Designed user interfaces for B2B SaaS applications serving 50K+ users. Conducted user research and usability testing to inform design decisions. Increased user task completion rate by 45% through interface improvements.",
      },
      {
        company: "E-commerce Startup",
        position: "Product Designer",
        startDate: "2020-02",
        endDate: "2021-07",
        description: "Redesigned mobile shopping experience, resulting in 30% increase in conversion rate. Created design system and component library. Collaborated with developers to ensure design implementation quality.",
      },
    ],
    education: [
      {
        school: "Art Institute of Portland",
        degree: "Bachelor of Fine Arts",
        field: "Graphic Design",
        graduationDate: "2020-05",
      },
    ],
    skills: [
      "Figma",
      "Sketch",
      "Adobe XD",
      "Photoshop",
      "Illustrator",
      "Prototyping",
      "User Research",
      "Wireframing",
      "Design Systems",
      "Accessibility",
    ],
  },
  // 新增模板 - DevOps工程师
  devops_engineer: {
    personalInfo: {
      name: "Chris Anderson",
      email: "chris.anderson@email.com",
      phone: "+1 (555) 678-9012",
      location: "Denver, CO",
      summary: "DevOps Engineer with 5+ years of experience building and maintaining scalable infrastructure. Expert in cloud platforms, containerization, and CI/CD pipelines. Passionate about automation and improving development workflows.",
    },
    experience: [
      {
        company: "CloudTech Solutions",
        position: "Senior DevOps Engineer",
        startDate: "2021-06",
        endDate: "2024-01",
        description: "Architected and managed AWS infrastructure supporting 99.9% uptime. Implemented Kubernetes clusters reducing deployment time by 60%. Led migration from monolith to microservices architecture.",
      },
      {
        company: "Software Company",
        position: "DevOps Engineer",
        startDate: "2019-01",
        endDate: "2021-05",
        description: "Built CI/CD pipelines using Jenkins and GitLab CI. Automated infrastructure provisioning with Terraform. Monitored system performance and implemented alerting solutions.",
      },
    ],
    education: [
      {
        school: "Colorado State University",
        degree: "Bachelor of Science",
        field: "Computer Engineering",
        graduationDate: "2018-12",
      },
    ],
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Jenkins",
      "GitLab CI",
      "Python",
      "Bash",
      "Monitoring",
      "Linux",
    ],
  },
  teacher: {
    personalInfo: {
      name: "李明",
      email: "liming@email.com",
      phone: "+86 138 0000 0000",
      location: "北京市海淀区",
      summary: "资深中学数学教师，拥有8年教学经验。擅长启发式教学，学生成绩提升显著。热爱教育事业，致力于培养学生的数学思维和解决问题的能力。",
    },
    experience: [
      {
        company: "北京市第一中学",
        position: "高中数学教师",
        startDate: "2018-09",
        endDate: "2024-01",
        description: "担任高三数学教师，所带班级高考数学平均分超过年级平均分15分。开发创新教学方法，获得市级优秀教师称号。指导学生参加数学竞赛，获得省级奖项。",
      },
      {
        company: "海淀区实验中学",
        position: "初中数学教师",
        startDate: "2016-09",
        endDate: "2018-08",
        description: "负责初二、初三数学教学工作。创建数学兴趣小组，提高学生学习积极性。参与教材编写工作，发表教学论文3篇。",
      },
    ],
    education: [
      {
        school: "北京师范大学",
        degree: "教育学学士",
        field: "数学教育",
        graduationDate: "2016-06",
      },
    ],
    skills: [
      "数学教学",
      "课程设计",
      "学生管理",
      "教学研究",
      "多媒体教学",
      "心理辅导",
      "团队协作",
      "沟通能力",
    ],
  },
  doctor: {
    personalInfo: {
      name: "Dr. 张华",
      email: "zhanghua@hospital.com",
      phone: "+86 139 0000 0000",
      location: "上海市黄浦区",
      summary: "内科主治医师，拥有6年临床经验。专长于心血管疾病诊治，发表SCI论文5篇。具备良好的医患沟通能力和团队协作精神。",
    },
    experience: [
      {
        company: "上海市第一人民医院",
        position: "内科主治医师",
        startDate: "2020-07",
        endDate: "2024-01",
        description: "负责心血管内科门诊和病房工作，年诊治患者2000+人次。参与科室疑难病例讨论，提出创新治疗方案。指导住院医师临床工作。",
      },
      {
        company: "复旦大学附属医院",
        position: "住院医师",
        startDate: "2018-07",
        endDate: "2020-06",
        description: "完成住院医师规范化培训，轮转各科室。参与急诊科工作，处理各类急危重症。协助上级医师完成手术和治疗工作。",
      },
    ],
    education: [
      {
        school: "复旦大学医学院",
        degree: "临床医学学士",
        field: "临床医学",
        graduationDate: "2018-06",
      },
    ],
    skills: [
      "临床诊断",
      "心血管疾病",
      "医学影像",
      "病历书写",
      "医患沟通",
      "急救技能",
      "医学研究",
      "团队协作",
    ],
  },
  designer: {
    personalInfo: {
      name: "陈美丽",
      email: "chenmeili@design.com",
      phone: "+86 137 0000 0000",
      location: "深圳市南山区",
      summary: "创意平面设计师，拥有5年品牌设计经验。擅长视觉识别系统设计、包装设计和数字媒体设计。作品曾获得国际设计奖项。",
    },
    experience: [
      {
        company: "创意设计工作室",
        position: "高级平面设计师",
        startDate: "2021-03",
        endDate: "2024-01",
        description: "负责品牌视觉设计，服务客户包括知名互联网公司和传统企业。设计的品牌形象获得客户一致好评，项目续约率达90%。",
      },
      {
        company: "广告传媒公司",
        position: "平面设计师",
        startDate: "2019-06",
        endDate: "2021-02",
        description: "参与大型广告项目设计，包括户外广告、宣传册、网站设计等。与客户密切沟通，确保设计方案符合品牌调性。",
      },
    ],
    education: [
      {
        school: "中央美术学院",
        degree: "设计学学士",
        field: "视觉传达设计",
        graduationDate: "2019-06",
      },
    ],
    skills: [
      "Adobe Creative Suite",
      "品牌设计",
      "包装设计",
      "网页设计",
      "插画设计",
      "摄影",
      "色彩搭配",
      "创意思维",
    ],
  },
  sales: {
    personalInfo: {
      name: "王强",
      email: "wangqiang@sales.com",
      phone: "+86 136 0000 0000",
      location: "广州市天河区",
      summary: "资深销售经理，拥有6年B2B销售经验。擅长客户关系管理和团队建设，连续3年超额完成销售目标。具备优秀的谈判技巧和市场洞察力。",
    },
    experience: [
      {
        company: "科技解决方案公司",
        position: "销售经理",
        startDate: "2020-01",
        endDate: "2024-01",
        description: "管理华南区域销售团队，年销售额达到2000万元。开发新客户50+家，客户续约率达85%。建立完善的销售流程和客户管理体系。",
      },
      {
        company: "软件服务公司",
        position: "销售代表",
        startDate: "2018-03",
        endDate: "2019-12",
        description: "负责企业级软件销售，年销售额500万元。维护重点客户关系，挖掘客户需求，提供定制化解决方案。",
      },
    ],
    education: [
      {
        school: "中山大学",
        degree: "市场营销学士",
        field: "市场营销",
        graduationDate: "2018-06",
      },
    ],
    skills: [
      "销售技巧",
      "客户关系管理",
      "商务谈判",
      "市场分析",
      "团队管理",
      "演讲能力",
      "CRM系统",
      "数据分析",
    ],
  },
  finance: {
    personalInfo: {
      name: "刘会计",
      email: "liukuaiji@finance.com",
      phone: "+86 135 0000 0000",
      location: "杭州市西湖区",
      summary: "注册会计师，拥有7年财务管理经验。精通财务分析、税务筹划和内控制度建设。曾为多家企业提供财务咨询服务，帮助企业优化财务结构。",
    },
    experience: [
      {
        company: "互联网科技公司",
        position: "财务经理",
        startDate: "2019-08",
        endDate: "2024-01",
        description: "负责公司财务管理工作，建立完善的财务制度和流程。参与公司融资项目，协助完成B轮融资5000万元。优化成本结构，降低运营成本15%。",
      },
      {
        company: "会计师事务所",
        position: "高级审计师",
        startDate: "2017-07",
        endDate: "2019-07",
        description: "参与上市公司年度审计工作，负责财务报表审计和内控测试。为客户提供财务咨询服务，协助企业规范财务管理。",
      },
    ],
    education: [
      {
        school: "上海财经大学",
        degree: "会计学学士",
        field: "会计学",
        graduationDate: "2017-06",
      },
    ],
    skills: [
      "财务分析",
      "税务筹划",
      "成本控制",
      "预算管理",
      "审计",
      "Excel高级应用",
      "财务软件",
      "风险管理",
    ],
  },
};